# Generated by Django 6.0.4 on 2026-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='watching',
            field=models.BooleanField(default=False),
        ),
    ]
