# Generated by Django 6.0.4 on 2026-06-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_cart_amount_cart_owned_cart_watching'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'listing')},
        ),
    ]
