# Generated by Django 6.0.4 on 2026-06-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_cart_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='owned',
        ),
        migrations.AddField(
            model_name='listing',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
